<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test4"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="45.567">
  <properties />
            <testcase name="loginTest" time="26.968" classname="JingDongProject.JDLoginPage">
                <failure type="java.lang.AssertionError"
                  message="检查点检查出错误"
              >
<![CDATA[java.lang.AssertionError: 检查点检查出错误
  org.testng.Assert.fail(Assert.java:94)
  menthod.CheckPointUtils.checkString(CheckPointUtils.java:59)
  JingDongProject.JDLoginPage.loginTest(JDLoginPage.java:127)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="loginTest" time="4.447" classname="JingDongProject.JDLoginPage" />
                <testcase name="loginTest" time="4.037" classname="JingDongProject.JDLoginPage" />
                <testcase name="loginTest" time="3.314" classname="JingDongProject.JDLoginPage" />
                <testcase name="loginTest" time="3.406" classname="JingDongProject.JDLoginPage" />
                <testcase name="loginTest" time="3.395" classname="JingDongProject.JDLoginPage" />
      
</testsuite>
